// Movie data - simulating external API response
export const MOVIES_DATA = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster_path: "images/shawshank-redemption.jpg",
    backdrop_path: "images/shawshank-bg.jpg",
    release_date: "1994-09-23",
    vote_average: 9.3,
    genre_ids: [18, 80],
    runtime: 142,
    genres: [{ name: "Drama" }, { name: "Crime" }],
    production_companies: ["Castle Rock Entertainment"],
    spoken_languages: [{ name: "English" }],
    budget: 25000000,
    revenue: 16000000,
  },
  {
    id: 2,
    title: "The Godfather",
    overview: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    poster_path: "images/godfather.jpg",
    backdrop_path: "images/godfather-bg.jpg",
    release_date: "1972-03-24",
    vote_average: 9.2,
    genre_ids: [18, 80],
    runtime: 175,
    genres: [{ name: "Drama" }, { name: "Crime" }],
    production_companies: ["Paramount Pictures"],
    spoken_languages: [{ name: "English" }],
    budget: 6000000,
    revenue: 245066411,
  },
  {
    id: 3,
    title: "The Dark Knight",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    poster_path: "images/dark-knight.jpg",
    backdrop_path: "images/dark-knight-bg.jpg",
    release_date: "2008-07-18",
    vote_average: 9.0,
    genre_ids: [28, 80, 18],
    runtime: 152,
    genres: [{ name: "Action" }, { name: "Crime" }, { name: "Drama" }],
    production_companies: ["Warner Bros. Pictures"],
    spoken_languages: [{ name: "English" }],
    budget: 185000000,
    revenue: 1004558444,
  },
  {
    id: 4,
    title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    poster_path: "images/pulp-fiction.jpg",
    backdrop_path: "images/pulp-fiction-bg.jpg",
    release_date: "1994-10-14",
    vote_average: 8.9,
    genre_ids: [80, 18],
    runtime: 154,
    genres: [{ name: "Crime" }, { name: "Drama" }],
    production_companies: ["Miramax Films"],
    spoken_languages: [{ name: "English" }],
    budget: 8000000,
    revenue: 214179088,
  },
  {
    id: 5,
    title: "Forrest Gump",
    overview: "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man.",
    poster_path: "images/forrest-gump.jpg",
    backdrop_path: "images/forrest-gump-bg.jpg",
    release_date: "1994-07-06",
    vote_average: 8.8,
    genre_ids: [18, 35],
    runtime: 142,
    genres: [{ name: "Drama" }, { name: "Comedy" }],
    production_companies: ["Paramount Pictures"],
    spoken_languages: [{ name: "English" }],
    budget: 55000000,
    revenue: 677387716,
  },
  {
    id: 6,
    title: "Inception",
    overview: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
    poster_path: "images/inception.jpg",
    backdrop_path: "images/inception-bg.jpg",
    release_date: "2010-07-16",
    vote_average: 8.7,
    genre_ids: [28, 878, 53],
    runtime: 148,
    genres: [{ name: "Action" }, { name: "Science Fiction" }, { name: "Thriller" }],
    production_companies: ["Warner Bros. Pictures"],
    spoken_languages: [{ name: "English" }],
    budget: 160000000,
    revenue: 836836967,
  },
  {
    id: 7,
    title: "The Matrix",
    overview: "A computer programmer discovers that reality as he knows it is a simulation and joins a rebellion to free humanity.",
    poster_path: "images/matrix.jpg",
    backdrop_path: "images/matrix-bg.jpg",
    release_date: "1999-03-31",
    vote_average: 8.7,
    genre_ids: [28, 878],
    runtime: 136,
    genres: [{ name: "Action" }, { name: "Science Fiction" }],
    production_companies: ["Warner Bros. Pictures"],
    spoken_languages: [{ name: "English" }],
    budget: 63000000,
    revenue: 463517383,
  },
  {
    id: 8,
    title: "Goodfellas",
    overview: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.",
    poster_path: "images/goodfellas.jpg",
    backdrop_path: "images/goodfellas-bg.jpg",
    release_date: "1990-09-21",
    vote_average: 8.7,
    genre_ids: [18, 80],
    runtime: 146,
    genres: [{ name: "Drama" }, { name: "Crime" }],
    production_companies: ["Warner Bros. Pictures"],
    spoken_languages: [{ name: "English" }],
    budget: 25000000,
    revenue: 46836394,
  },
  {
    id: 9,
    title: "Interstellar",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster_path: "images/interstellar.jpg",
    backdrop_path: "images/interstellar-bg.jpg",
    release_date: "2014-11-07",
    vote_average: 8.6,
    genre_ids: [18, 878],
    runtime: 169,
    genres: [{ name: "Drama" }, { name: "Science Fiction" }],
    production_companies: ["Paramount Pictures"],
    spoken_languages: [{ name: "English" }],
    budget: 165000000,
    revenue: 677471339,
  },
  {
    id: 10,
    title: "The Lord of the Rings: The Return of the King",
    overview: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam.",
    poster_path: "images/lord-of-the-rings.jpg",
    backdrop_path: "images/lor-bg.jpg",
    release_date: "2003-12-17",
    vote_average: 8.9,
    genre_ids: [12, 18, 14],
    runtime: 201,
    genres: [{ name: "Adventure" }, { name: "Drama" }, { name: "Fantasy" }],
    production_companies: ["New Line Cinema"],
    spoken_languages: [{ name: "English" }],
    budget: 94000000,
    revenue: 1140682011,
  },
  {
    id: 11,
    title: "Fight Club",
    overview: "An insomniac office worker and a devil-may-care soap maker form an underground fight club.",
    poster_path: "images/fightclub.jpg",
    backdrop_path: "images/fightclub-bg.jpg",
    release_date: "1999-10-15",
    vote_average: 8.8,
    genre_ids: [18],
    runtime: 139,
    genres: [{ name: "Drama" }],
    production_companies: ["20th Century Fox"],
    spoken_languages: [{ name: "English" }],
    budget: 63000000,
    revenue: 100853753,
  },
  {
    id: 12,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.",
    poster_path: "images/lor-fellowship.webp",
    backdrop_path: "images/fellowship.bg.png",
    release_date: "2001-12-19",
    vote_average: 8.8,
    genre_ids: [12, 18, 14],
    runtime: 178,
    genres: [{ name: "Adventure" }, { name: "Drama" }, { name: "Fantasy" }],
    production_companies: ["New Line Cinema"],
    spoken_languages: [{ name: "English" }],
    budget: 93000000,
    revenue: 871530324,
  },
  {
    id: 13,
    title: "Star Wars: Episode V - The Empire Strikes Back",
    overview: "After the Rebels are brutally overpowered by the Empire, Luke Skywalker begins Jedi training with Yoda.",
    poster_path: "images/starwars.jpg",
    backdrop_path: "images/starwars-bg.jpg",
    release_date: "1980-05-21",
    vote_average: 8.7,
    genre_ids: [12, 28, 878],
    runtime: 124,
    genres: [{ name: "Adventure" }, { name: "Action" }, { name: "Science Fiction" }],
    production_companies: ["Lucasfilm"],
    spoken_languages: [{ name: "English" }],
    budget: 18000000,
    revenue: 538375067,
  },
  {
    id: 14,
    title: "One Flew Over the Cuckoo's Nest",
    overview: "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse.",
    poster_path: "images/oneflew.jpg",
    backdrop_path: "images/oneflew-bg.jpg",
    release_date: "1975-11-19",
    vote_average: 8.7,
    genre_ids: [18],
    runtime: 133,
    genres: [{ name: "Drama" }],
    production_companies: ["United Artists"],
    spoken_languages: [{ name: "English" }],
    budget: 3000000,
    revenue: 108981275,
  },
  {
    id: 15,
    title: "Parasite",
    overview: "A poor family schemes to become employed by a wealthy family and infiltrate their household.",
    poster_path: "images/parasite.png",
    backdrop_path: "images/parasite-bg.jpg",
    release_date: "2019-05-30",
    vote_average: 8.6,
    genre_ids: [35, 53, 18],
    runtime: 132,
    genres: [{ name: "Comedy" }, { name: "Thriller" }, { name: "Drama" }],
    production_companies: ["CJ Entertainment"],
    spoken_languages: [{ name: "Korean" }],
    budget: 11400000,
    revenue: 258662776,
  },
];

// Genre mapping
export const GENRE_MAP = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
};

// Fetch movies data (simulating API call)
export async function fetchMoviesData() {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  return MOVIES_DATA;
}

// Get genre names from genre IDs
export function getGenreNames(genreIds) {
  return genreIds.map(id => ({ name: GENRE_MAP[id] || "Unknown" }));
}

// Get movie by ID
export function getMovieById(movieId) {
  return MOVIES_DATA.find(movie => movie.id === movieId);
}